public class DemoDeployment {
    public static void method(){
        system.debug('Welcome to Varsha Educational Academy..');
        system.debug('Bootcamp is soon..');
        system.debug('Hii Everyone by varsha..');
        system.debug('Hii Everyone by varsha..');
        system.debug('Hii Everyone by varsha..');
        system.debug('Hii Everyone by varsha..');
        system.debug('Hii Everyone by varsha..');


        system.debug('Hii Everyofdgrtrne by varsha..');

        system.debug('Hii new by varsha..');
    }
}
